//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salem.Data.Salem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Round
    {
        public int Id { get; set; }
        public int GameSessionId { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string KillVote { get; set; }
        public string SaveVote { get; set; }
    
        public virtual GameSession GameSession { get; set; }
    }
}
